[versions]
corePlugins = "1.0.2"
coreDomain = "1.0.0"
coreData = "1.0.0"
coreCompose = "1.0.1"

financeTheme = "1.0.2"
financeLaunch = "1.0.2"

provideNetworking = "1.0.0"

charty = "Beta-0.0.5"

[libraries]
corePlugins = { group = "vn.core.libs", name = "plugins", version.ref = "corePlugins" }
coreDomain = { group = "vn.core.libs", name = "domain", version.ref = "coreDomain" }
coreData = { group = "vn.core.libs", name = "data", version.ref = "coreData" }
coreCompose = { group = "vn.core.libs", name = "compose", version.ref = "coreCompose" }

provideNetworking = { group = "vn.core.provider", name = "finance-networking", version.ref = "provideNetworking" }
financeTheme = { group = "vn.finance.libs", name = "theme", version.ref = "financeTheme" }
financeLaunch = { group = "vn.finance.libs", name = "feature-launch", version.ref = "financeLaunch" }

charty = { group = "io.github.thechance101", name = "chart", version.ref = "charty" }

[plugins]
