name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Source
    runs-on: ubuntu-latest
    env:
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_REPO_NAME: ${{ secrets.GH_REPO_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Demo
        run: ./gradlew :demo:build

      - name: Build Presentation
        run: ./gradlew :statistic:presentation:build

      - name: Build Business
        run: ./gradlew :statistic:business:build

      - name: Build Api
        run: ./gradlew :statisticApi:build

      - name: Sending report to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 🚀 Group com.feature.template build successfully!